# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "radiant-language_redirect-extension"
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Giovanni Intini", "Andrew vonderLuft"]
  s.date = "2013-02-15"
  s.description = "Redirects to the appropriate language section based on the content encoding preferred by the Web browser."
  s.email = "avonderluft@avlux.net"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/models/language_redirect_page.rb",
    "language_redirect_extension.rb",
    "lib/language_redirect_tags.rb",
    "lib/tasks/language_redirect_extension_tasks.rake",
    "radiant-language_redirect-extension.gemspec",
    "spec/datasets/language_redirect_dataset.rb",
    "spec/models/language_redirect_page_spec.rb",
    "spec/models/tags_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/avonderluft/radiant-language_redirect-extension"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Language Redirect Extension for Radiant CMS"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 1.1.3"])
    else
      s.add_dependency(%q<radiant>, [">= 1.1.3"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 1.1.3"])
  end
end

